import numpy as np
import math

# Parametry
N = 256
SCALE = 1 << 14  # 2^14 = 16384

# Generowanie współczynników
n = np.arange(N//2)  # Tylko pierwsza połowa (ze względu na symetrię)
cos_values = np.round(SCALE * np.cos(2 * np.pi * n / N))
sin_values = np.round(-SCALE * np.sin(2 * np.pi * n / N))  # -sin ze względu na konwencję FFT

# Funkcja do formatowania wartości dla SystemVerilog
def format_for_sv(values, values_per_line=8, indent=8):
    lines = []
    for i in range(0, len(values), values_per_line):
        chunk = values[i:i+values_per_line]
        line = ", ".join(f"{int(x):6d}" for x in chunk)
        if i + values_per_line < len(values):
            line += ","
        lines.append(" " * indent + line)
    return "\n".join(lines)

# Generowanie kodu SystemVerilog
sv_code = f"""
// Automatically generated by Python script
localparam logic signed [15:0] W_real[0:{N//2-1}] = '{{
{format_for_sv(cos_values)}
}};

localparam logic signed [15:0] W_imag[0:{N//2-1}] = '{{
{format_for_sv(sin_values)}
}};
"""

print(sv_code)

# Zapisz do pliku (opcjonalnie)
with open("fft256_twiddle_factors.sv", "w") as f:
    f.write(sv_code)